name: Java CI with gradle

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    builds:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set Up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Grant execute permissions for gradle
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

